DROP DATABASE IF EXISTS ENCOUNTERTOOLS;
CREATE DATABASE ENCOUNTERTOOLS;
USE ENCOUNTERTOOLS;

DROP TABLE IF EXISTS NON_PLAYABLE_CHARACTER;
DROP TABLE IF EXISTS ALIGNMENTS;
DROP TABLE IF EXISTS BACKGROUNDS;
DROP TABLE IF EXISTS NAMES;

DROP TABLE IF EXISTS CHARACTERISTICS;
DROP TABLE IF EXISTS MANNERISMS;
DROP TABLE IF EXISTS TRAITS;
DROP TABLE IF EXISTS APPEARANCES;
DROP TABLE IF EXISTS BONDS;
DROP TABLE IF EXISTS FLAWS;
DROP TABLE IF EXISTS IDEALS;

DROP TABLE IF EXISTS MONSTERS;

DROP TABLE IF EXISTS MAGIC_ITEMS;
DROP TABLE IF EXISTS ITEM_EFFECTS;
DROP TABLE IF EXISTS ADVENTURING_GEAR;
DROP TABLE IF EXISTS ARMORS;
DROP TABLE IF EXISTS WEAPONS;

DROP TABLE IF EXISTS ENVIRONMENTAL_EFFECTS;
DROP TABLE IF EXISTS XP_THRESHOLDS;
DROP TABLE IF EXISTS DIFFICULTY;
-- endregion

-- region DDL

-- region Environmental Effects
CREATE TABLE DIFFICULTY(
    DIFFICULTY_ID INT PRIMARY KEY ,
    MIN_SAVE TINYINT NOT NULL,
    MAX_SAVE TINYINT NOT NULL,
    MIN_ATTACK_BONUS TINYINT NOT NULL,
    MAX_ATTACK_BONUS TINYINT NOT NULL,
    DANGER VARCHAR(10) NOT NULL,
    DIF_FROM_1_4 VARCHAR(5) NOT NULL,
    DIF_FROM_5_10 VARCHAR(5) NOT NULL,
    DIF_FROM_11_16 VARCHAR(5) NOT NULL,
    DIF_FROM_17_20 VARCHAR(5) NOT NULL
);

CREATE TABLE XP_THRESHOLDS(
    LEVEL TINYINT PRIMARY KEY ,
    EASY_XP SMALLINT,
    MEDIUM_XP SMALLINT,
    HARD_XP SMALLINT,
    DEADLY_XP SMALLINT
);

CREATE TABLE ENVIRONMENTAL_EFFECTS(
    ENVIRON_EFFECT_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NULL ,
    EFFECT_DESC VARCHAR(2000) NULL ,
    ENVIRONMENT VARCHAR(11) NULL ,
    DIFFICULTY_ID INT DEFAULT(0),
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0) ,
    FOREIGN KEY (DIFFICULTY_ID) REFERENCES DIFFICULTY(DIFFICULTY_ID)
);
-- endregion

-- region Items
CREATE TABLE ADVENTURING_GEAR(
    GEAR_ID INT AUTO_INCREMENT  ,
    TYPE VARCHAR(20) DEFAULT '' ,
    NAME VARCHAR(30) NOT NULL ,
    COST INT NULL ,
    WEIGHT FLOAT NULL ,
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0) ,
    PRIMARY KEY (GEAR_ID, TYPE)
);

CREATE TABLE ARMORS(
    ARMOR_ID INT AUTO_INCREMENT  ,
    TYPE VARCHAR(20) DEFAULT '' ,
    NAME VARCHAR(25) NOT NULL ,
    COST INT NULL ,
    WEIGHT FLOAT NULL ,
    BASE_AC TINYINT NULL ,
    AC_MAX_BONUS TINYINT DEFAULT(0) ,
    STEALTH BOOL DEFAULT(FALSE),
    STR_REQ TINYINT DEFAULT(0),
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0) ,
    PRIMARY KEY (ARMOR_ID, TYPE)
);

CREATE TABLE WEAPONS(
    WEAPON_ID INT AUTO_INCREMENT ,
    TYPE VARCHAR(20) DEFAULT '',
    NAME VARCHAR(20) NOT NULL ,
    COST INT NULL ,
    WEIGHT FLOAT NULL ,
    DAMAGE_DICE VARCHAR(5) NULL ,
    DAMAGE_TYPE VARCHAR(8) NULL ,
    PROPERTIES VARCHAR(100) NULL ,
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0) ,
    PRIMARY KEY (WEAPON_ID, TYPE)
);

CREATE TABLE ITEM_EFFECTS(
    EFFECT_ID INT PRIMARY KEY AUTO_INCREMENT,
    F_NAME VARCHAR(20) NOT NULL ,
    L_NAME VARCHAR(25) NOT NULL ,
    TYPE VARCHAR(1) NOT NULL DEFAULT '' ,
    ATTUNEMENT_REQ BOOL DEFAULT(FALSE),
    DESCRIPTION VARCHAR(475) NULL ,
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0)
);

-- endregion

-- region Monsters
CREATE TABLE ALIGNMENTS(
    ALIGNMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    ALIGNMENT VARCHAR(2) NOT NULL
);

CREATE TABLE MONSTERS(
    MONSTER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30),
    SIZE VARCHAR(10),
    TYPE VARCHAR(11),
    ALIGNMENT VARCHAR(2),
    AC SMALLINT,
    HP SMALLINT,
    CR FLOAT,
    XP INT,
    ENVIRONMENT VARCHAR(11),
    IS_LEGENDARY BOOL,
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0)
);
-- endregion

-- region Characteristics
CREATE TABLE TRAITS(
    TRAIT_ID INT PRIMARY KEY AUTO_INCREMENT,
    TRAIT_DESC VARCHAR(140),
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0)
);

CREATE TABLE IDEALS(
    IDEAL_ID INT PRIMARY KEY AUTO_INCREMENT,
    IDEAL_DESC VARCHAR(140),
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0)
);

CREATE TABLE BONDS(
    BOND_ID INT PRIMARY KEY AUTO_INCREMENT,
    BOND_DESC VARCHAR(130),
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0)
);

CREATE TABLE FLAWS(
    FLAW_ID INT PRIMARY KEY AUTO_INCREMENT,
    FLAW_DESC VARCHAR(120),
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0)
);

CREATE TABLE APPEARANCES(
    APPEARANCE_ID INT PRIMARY KEY AUTO_INCREMENT,
    APPEARANCE_DESC VARCHAR(60),
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0)
);

CREATE TABLE MANNERISMS(
    MANNERISM_ID INT PRIMARY KEY AUTO_INCREMENT,
    MANNERISM_DESC VARCHAR(150),
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0)
);

-- endregion

-- region NPC
CREATE TABLE BACKGROUNDS(
    BACKGROUND_ID INT PRIMARY KEY AUTO_INCREMENT,
    BACKGROUND_NAME VARCHAR(20),
    BACKGROUND_DESC VARCHAR(650),
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0)
);

CREATE TABLE NAMES(
    NAME_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20),
    TYPE VARCHAR(1),
    RACE VARCHAR(10),
    BOOK VARCHAR(10) NOT NULL,
    PAGE TINYINT DEFAULT(0)
);

-- endregion

-- endregion
